### ISSUE TITLE
Github Actions: Adopt JDK distribution is no longer maintained

### ISSUE THREAD

**Issue by RSBat** [ankidroid/Anki-Android#11992]
I was copying Github actions for tests from your project and noticed that you use `adopt` distribution:
```
      - name: Configure JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11" # ubuntu-latest is about to default to 11, force it everywhere
```

According to the [docs](https://github.com/marketplace/actions/setup-java-jdk#supported-distributions)

> Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from `adopt` to `temurin` to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
