### ISSUE TITLE
[security] Setup CodeQL for `java-kotlin`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16286]
```
  [2024-04-21 16:44:07] [autobuild] ERROR: AnkiDroid builds with JVM version 17 or 21.
  [2024-04-21 16:44:07] [autobuild]   Incompatible major version detected: '11'
```

https://github.com/ankidroid/Anki-Android/actions/runs/8774109064

I believe this should be defined by `codeql-analysis.yml`. We are currently using default values, and this seems to not have been created.

----

According to https://redirect.github.com/github/codeql-action/issues/97 , we can use: `setup-java`, I suspect:

```yaml
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
```
