### ISSUE TITLE
Top side of card is cut off when "Center align" enabled & content is long

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#17998]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. "Settings" > "Appearance" > Enable "Center align"
2. Show cards with content that is too long to show without scrolling, like the following ones except for Pattern A.
 
Pattern A | Pattern B | Pattern C | Pattern D
---|---|---|---
Front: short, Back: short | Front: short, Back: long | Front: long, Back: short | Front: long, Back: long
![Image](https://github.com/user-attachments/assets/33e9e82f-843c-410c-a571-c558694fde4c) | ![Image](https://github.com/user-attachments/assets/e88f3c45-b4ea-48d8-b3dd-86ec532cc8c8) | ![Image](https://github.com/user-attachments/assets/d6855c12-1125-4341-a798-4440bed772e3) | ![Image](https://github.com/user-attachments/assets/7b74ded9-21de-4ff0-b1b3-1e8d1eb71c40)

------
**Results**
-- |Start|Scroll to Top|Show Answer|Scroll to Top
---|---|---|---|----
**Pattern A** (front: short, back: short)| OK![Image](https://github.com/user-attachments/assets/75a01406-b763-4f28-9db2-303bdc33bb95) | OK (No need) ![Image](https://github.com/user-attachments/assets/75a01406-b763-4f28-9db2-303bdc33bb95) | OK ![Image](https://github.com/user-attachments/assets/4d8796ab-c551-4534-96d7-0acd70b06380) | OK (No need) ![Image](https://github.com/user-attachments/assets/4d8796ab-c551-4534-96d7-0acd70b06380) 
**Pattern B** (front: short, back: long)| OK ![Image](https://github.com/user-attachments/assets/2de8691d-bece-467f-8ec4-eff4f9fc0aff) | OK (No need) ![Image](https://github.com/user-attachments/assets/2de8691d-bece-467f-8ec4-eff4f9fc0aff)| **NG** (The beginning of Back is not shown) ![Image](https://github.com/user-attachments/assets/6e20b418-e5cc-4dd5-8694-ad4d76054704) | **Bad** (impossible) ![Image](https://github.com/user-attachments/assets/930b68c2-dfbf-4b7e-8ff3-dc673340a61f)
**Pattern C** (front: long, back: short)| **NG** (The beginning of Front is not shown) ![Image](https://github.com/user-attachments/assets/c1895c80-74e0-46e1-9722-c0f6a8e15da9) | **Bad** (impossible) ![Image](https://github.com/user-attachments/assets/c1584614-3e50-47a5-b1a5-fff6e586e23c) | OK (The beginning of Back is shown) ![Image](https://github.com/user-attachments/assets/801085fb-87b5-48ba-a115-332a9b4b691f) | **Bad** (impossible) ![Image](https://github.com/user-attachments/assets/e58aab59-65f5-4134-858d-1522703f1c5f)
**Pattern D** (front: long, back: long)| **NG** (The beginning of Front is not shown) ![Image](https://github.com/user-attachments/assets/3dcf8657-9991-42ab-895e-c369e2bcdd97) | **Bad** (impossible) ![Image](https://github.com/user-attachments/assets/ccdd8429-8a9e-4861-af7d-a6f0bc65d8d2) | OK (The beginning of Back is shown) ![Image](https://github.com/user-attachments/assets/c4923471-aa65-4067-99b6-7e371a5e6d82) | **Bad** (impossible) ![Image](https://github.com/user-attachments/assets/af42ea29-c631-4fbb-8f6d-b7731fc86991)

### Expected behaviour

User can scroll to top of the cards

### Debug info

```text
AnkiDroid Version = 2.21alpha11 (b0d7b48431676f1ee721b4cae16065d50af0425a)
Backend Version = 0.1.49-anki25.01rc1 (25.01rc1 b65fa693dacbd92c0bdd2a8c3800d0827432d108)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.163 Mobile Safari/537.36
ACRA UUID = dae56c60-345e-41f3-a616-f02ce05cd8ad
FSRS = 2.0.2 (Enabled: false)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Scrolling to bottom works properly in all cases.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CNG** [comment]
Ah, disabling that setting solves my problem of suddenly not being able to see the top of many of my cards. In the past I had vertically centered with my own CSS but removed that a year or two ago due to difficulty keeping it working. So I no longer use vertical centering, but did not notice this setting. Maybe it's new? Anyway, turning it off fixed my issue. Thanks!

**Comment by FubayashiKazue** [comment]
I have "center align"  disabled by default, by still experience the same behaviour (long answer is being cut off at the top and I can't scroll up, only down). Don't know exactly when it started, but the cards worked fine before.

**Comment by snowtimeglass** [comment]
@FubayashiKazue Can you paste the templates and the styling of the card type of the card here?

Steps to copy them:
1. Show the card in the reviewer screen
2. Tap the three-dots button
3. Tap `Edit note`
4. Tap `Cards: blah blah` (e.g., `Cards: Card 1`) 
    (then, `Card types` screen gets shown.)
6. Tap the three-dots button
7. Tap `Copy as Markdown`

**Comment by FubayashiKazue** [comment]
It's a template from a shared Japanese grammar deck with some javascript so that only 3 random sentences are shown on the front side. This is the "faulty" backside scrolled to the top as much as possible, only the bottom part of the "explanation box" is visible:

![Image](https://github.com/user-attachments/assets/333dac24-680c-4ef0-95c3-8191868e01ba)

**Front template**

```html
<!-- Use this to assist in making changes: http://codepen.io/hssm/pen/rrrkpR -->

<div id="questionSide">
  <div id="concept">
    {{文型}}
  </div>
  <!-- We fill this in with JavaScript -->
  <div id="questionBox"></div>
  <div id="answerBox">
     {{#例文1}}
    <div class="example">
      <div class="example_jp">{{例文1}}</div>
    </div>
    {{/例文1}} {{#例文2}}
    <div class="example">
      <div class="example_jp">{{例文2}}</div>
    </div>
    {{/例文2}} {{#例文3}}
    <div class="example">
      <div class="example_jp">{{例文3}}</div>
    </div>
    {{/例文3}} {{#例文4}}
    <div class="example">
      <div class="example_jp">{{例文4}}</div>
    </div>
    {{/例文4}} {{#例文5}}
    <div class="example">
      <div class="example_jp">{{例文5}}</div>
    </div>
    {{/例文5}} {{#例文6}}
    <div class="example">
      <div class="example_jp">{{例文6}}</div>
    </div>
    {{/例文6}} {{#例文7}}
    <div class="example">
      <div class="example_jp">{{例文7}}</div>
    </div>
    {{/例文7}} {{#例文8}}
    <div class="example">
      <div class="example_jp">{{例文8}}</div>
    </div>
    {{/例文8}} {{#例文9}}
    <div class="example">
      <div class="example_jp">{{例文9}}</div>
    </div>
    {{/例文9}} {{#例文10}}
    <div class="example">
      <div class="example_jp">{{例文10}}</div>
    </div>
    {{/例文10}} {{#例文11}}
    <div class="example">
      <div class="example_jp">{{例文11}}</div>
    </div>
    {{/例文11}} {{#例文12}}
    <div class="example">
      <div class="example_jp">{{例文12}}</div>
    </div>
    {{/例文12}} {{#例文13}}
    <div class="example">
      <div class="example_jp">{{例文13}}</div>
    </div>
    {{/例文13}} {{#例文14}}
    <div class="example">
      <div class="example_jp">{{例文14}}</div>
    </div>
    {{/例文14}} {{#例文15}}
    <div class="example">
      <div class="example_jp">{{例文15}}</div>
    </div>
    {{/例文15}}

    <script>
      // Make a mutable array of fields
      var fields = [];
      var nodes = document.getElementsByClassName("example");
      for (i = 0; i < nodes.length; i++) {
        fields.push(nodes[i]);
      }
      var count = 3;
      
      // Here is some garbage for ensuring the random indices are
      // the same for each day and different for each card.
      // -- --
      var oneDayInMs = 1000 * 60 * 60 * 24;
      var currentTimeInMs = new Date().getTime();
      var timeInDays = Math.floor(currentTimeInMs / oneDayInMs);
      var numberForToday = timeInDays % 9999;
      // This should be """"random enough""""
      var seed = numberForToday + fields[0].innerHTML.length;
      function random() {
        var x = Math.sin(seed++) * 10000;
        return x - Math.floor(x);
      }
      // -- End of garbage --
  
      // Pluck out random examples and insert them in our question container
      var qBox = document.getElementById("questionBox");
      for (i = 0; i < count; i++) {
        // Min:Max = 1:field.length-1
        var r = Math.floor(random() * fields.length - 1) + 1;
        qBox.appendChild(fields[r]);
        fields.splice(r, 1); // Remove to avoid dupes
      }
    </script>
  </div>
</div>
```

**Back template**

```html
<div id="answerSide">
  <div id="answerBox">
    <!-- Anchor to this on card flip -->
    <div id="answer"></div>
	<div id="concept">
    {{文型}}
    </div>
    <div id="usage"><span class ="definition">
<strong>意味</strong><br>
	{{意味}}<br>
	{{#接続}}<br><strong>接続</strong><br>{{furigana:接続}}<br>{{/接続}}
	{{#備考}}<br><strong>備考</strong><br>{{備考}}<br>{{/備考}}
	</span>
	</div>
     {{#例文1}}
    <div class="example">
      <div class="example_jp">{{例文1}}</div>
    </div>
    {{/例文1}} {{#例文2}}
    <div class="example">
      <div class="example_jp">{{例文2}}</div>
    </div>
    {{/例文2}} {{#例文3}}
    <div class="example">
      <div class="example_jp">{{例文3}}</div>
    </div>
    {{/例文3}} {{#例文4}}
    <div class="example">
      <div class="example_jp">{{例文4}}</div>
    </div>
    {{/例文4}} {{#例文5}}
    <div class="example">
      <div class="example_jp">{{例文5}}</div>
    </div>
    {{/例文5}} {{#例文6}}
    <div class="example">
      <div class="example_jp">{{例文6}}</div>
    </div>
    {{/例文6}} {{#例文7}}
    <div class="example">
      <div class="example_jp">{{例文7}}</div>
    </div>
    {{/例文7}} {{#例文8}}
    <div class="example">
      <div class="example_jp">{{例文8}}</div>
    </div>
    {{/例文8}} {{#例文9}}
    <div class="example">
      <div class="example_jp">{{例文9}}</div>
    </div>
    {{/例文9}} {{#例文10}}
    <div class="example">
      <div class="example_jp">{{例文10}}</div>
    </div>
    {{/例文10}} {{#例文11}}
    <div class="example">
      <div class="example_jp">{{例文11}}</div>
    </div>
    {{/例文11}} {{#例文12}}
    <div class="example">
      <div class="example_jp">{{例文12}}</div>
    </div>
    {{/例文12}} {{#例文13}}
    <div class="example">
      <div class="example_jp">{{例文13}}</div>
    </div>
    {{/例文13}} {{#例文14}}
    <div class="example">
      <div class="example_jp">{{例文14}}</div>
    </div>
    {{/例文14}} {{#例文15}}
    <div class="example">
      <div class="example_jp">{{例文15}}</div>
    </div>
    {{/例文15}}
  </div>
</div>
```

**Styling**

```css
@font-face {
	src: url('_kosugiMaru-Regular.ttf'); 
    font-family: 'Kosugi Maru';
}

html { height: 100%; }
.card {
  height: 100%;
  display: -webkit-box;
  -webkit-box-align: stretch;
  -webkit-box-pack: center;
  -webkit-box-orient: vertical;
  margin: 0;
  padding: 0;
  font-family: 'Kosugi Maru', sans-serif;
  text-align: left;
  font-size: 15px;
  line-height: 1.3;
}

.definition {
 font-size: 18px;
 text-align: left; 
}

#concept {
  width: 80%;
  margin: 3em auto 2em;
  font-size: 140%;
  #background-color: #222222;
  color: white;
  font-weight: bold;
  border-radius: 10px;
  padding: 0.2em 0;
  text-align: center; 
}

.example {
  position: relative;
  padding: 1em 0;
  margin: 0% 0% 0% 0%;
  border-radius: .3em;
  #background-color: #222222;
}

.example_jp > strong, .example_jp > b {
  color: #90ee90;
}

.example .example_jp {
  font-size: 140%;
  #color: #346;
  text-align: left; 
}

#usage {
  padding: 3% 3%;
  margin: 0% 3%;
  #color: #000;
  #background-color: #222222;
  border: solid grey;
  border-radius: 10px;
}

#answer {
    position: relative;
    top: -1em;
  
}

/* Make better use of space when on mobile. */
@media screen and (orientation:portrait) {
  .mobile #content { margin: 0; }
  .mobile .example {
    font-size: 85%;
    margin: 1% 0.5%;
  }
}

/* Hide the answer side if we're on the question side. */
:not(#answerSide) > #questionSide #answerBox {
  display: none;
}
```
