### ISSUE TITLE
What is the DOM structure Anki Droid use to render user template? (I fail to apply some style)

### ISSUE THREAD

**Issue by freMea** [ankidroid/Anki-Android#5269]
### Reproduction Steps

I made a responsive material design template using flexbox. It works on desktop applying the flex display to `#qa`. Because, basically, Anki destop DOM is:

```html
<body class="card card1">
  <div id="qa">
```
followed by my template (_example for the back_)
```html
    <div class="front front-back">
      <div class="number">0</div>
      <a class="show_hint" href="#" title="Montrer Indice" onclick="this.style.display = 'none';var el=document.getElementById('hint');el.classList.add('hint');el.style.display='inline-block';return false;"></a>
      <div id="hint" style="display: none">Personnage de film</div>
    </div>

    <div class="back">
      <figure class="vignette">
        <img src="paste-3feb872947d053139d5f661fdfcd71d007ae2e45.jpg" draggable="false">
        <figcaption class="img_legend">James Bond 007</figcaption>
      </figure>
    </div>
```

### Expected Result
With this kind of CSS on desktop:
```CSS
#qa, .card {
  min-height: 100vh !important;
  max-height: 100vh !important;
  min-width: 100vw !important;
  max-width: none !important;

  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  justify-content: center;
  align-content: center;
  align-items: stretch;

  background-color: transparent;
  color: white;
  font-family: "roboto medium", sans-serif;
  font-size: 2rem;
  text-align: center;
  margin: 0 !important;
  padding: 0 !important;
}
```

front | back
--- | ---
![](https://i.snag.gy/xd1hcp.jpg) | ![](https://i.snag.gy/Nd4Cug.jpg)

### Actual Result
I tried to edit my CSS following the [Advanced formatting](https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting) help section to no avail:

```CSS
#qa, .card, .mobile, .mobile #content, .mobile .card {
  min-height: 100vh !important;
  max-height: 100vh !important;
  min-width: 100vw !important;
  max-width: none !important;

  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  justify-content: center;
  align-content: center;
  align-items: stretch;

  background-color: transparent;
  color: white;
  font-family: "roboto medium", sans-serif;
  font-size: 2rem;
  text-align: center;
  margin: 0 !important;
  padding: 0 !important;
}

.mobile #content {
  background-color: blue;
}
```

front | back
--- | ---
![](https://i.snag.gy/okrnGW.jpg) | ![](https://i.snag.gy/bEp7uw.jpg)

**Of course I refresh the media with an addon before syncing so Anki Droid always take the last CSS files in account.** Hence, I’m sure I use the same CSS file as in desktop at every test.

### Debug info

```
[AnkiDroid Version = 2.8.4

Android Version = 9

ACRA UUID = cce85e92-250e-4aa0-9955-4e495676f57d](url)
```

### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting an enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
