### ISSUE TITLE
"Notify when" notifications don't trigger 

### ISSUE THREAD

**Issue by tilusnet** [ankidroid/Anki-Android#6552]
###### Reproduction Steps

1. Activate a Notify when X cards are due setting
2. Assume X cards are due
3. Notification does not show unless I manually start the app. 

###### Expected Result

Notification to appear automatically, regardless of app state. 

###### Actual Result
Notification only appears when app is started manually. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for logging this @tilusnet - there are a few notifications issues right now, and that area of the code hasn't received attention in a while. We'll do a scan through there soon but unless someone else volunteers, "soon" might be a few months

**Comment by tilusnet** [comment]
Thanks for the update @mikehardy.
For the time being I have a hint ─ not sure if it helps narrowing down problems: since I added Anki widgets to my home screen, the notifications started happening!

**Comment by vitlinda** [comment]
> Thanks for the update @mikehardy.
> For the time being I have a hint ─ not sure if it helps narrowing down problems: since I added Anki widgets to my home screen, the notifications started happening! 

Doesn't work anymore after the last update (v2.17)

**Comment by flexagoon** [comment]
@tilusnet are there any plans to work on this soon? This is the single biggest issue preventing me from using anki

**Comment by tilusnet** [comment]
> @tilusnet are there any plans to work on this soon? This is the single biggest issue preventing me from using anki

@flexagoon I'm not a coder.

**Comment by david-allison** [comment]
We'd like to get it working, but it's on the backlog currently

**Comment by julmey** [comment]
Can someone please fix this issue? There literally is close to no point in using a spaced repetition learning app if I can't learn the cards in the required intervals, because I forget to check daily.

There can simply not be any issue more important than this.

**Comment by lutzky** [comment]
My workaround: I use [homeassistant](https://www.home-assistant.io/), so I set up an automation:

```yaml
alias: Reminder to open Anki
description: >-
  Notifications are known to be broken:
  https://www.reddit.com/r/Anki/comments/13001vk/comment/jhucbgr/
triggers:
  - trigger: time
    at: "07:53:00"
conditions: []
actions:
  - action: notify.ohad_mobile
    data:
      message: >-
        Open Anki so it shows the notification about how many remaining cards
        you need.
      title: Open Anki
      data:
        clickAction: app://com.ichi2.anki
        icon_url: >-
          https://raw.githubusercontent.com/ankidroid/Anki-Android/main/docs/graphics/logos/ankidroid_logo.png
        channel: Anki
        importance: low
mode: single
```
