### ISSUE TITLE
Add ability to turn off Reviewer scrollbars via Javascript

### ISSUE THREAD

**Issue by trvs-lab** [ankidroid/Anki-Android#9701]
Excuse me, I wanna write some css or javascript code to hide the scrollbar, but I haven't find the right way yet. The code below works fine on anki desktop, but it doesn't work on ankidroid, anyone can help me?
```css
  ::-webkit-scrollbar { 
       width: 0 !important 
  }
```
